### PR TITLE
Build: Allow to pass custom browserSets to the testswarm* tasks

### PR DESCRIPTION
**Pull request by mzgol**
This is needed to be able to test UI with Core Git that doesn't support IE 8.

Ref gh-1646

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Can we just manage the browser set for git in the task directly? I'd prefer having that logic contained in the task instead of having to manage the external build settings.

**Comment by mzgol** [comment]
We can but it will be spread anyway as a browserSet with this name has to be defined in the infrastructure repository. Also, as new jQuery versions may drop further browsers, you may end up needing to hardcode more than one browserSet and keep it in sync with the infra repo.

Do you want me hardcode the browserSet for Core Git?

**Comment by scottgonzalez** [comment]
> We can but it will be spread anyway as a browserSet with this name has to be defined in the infrastructure repository.

That's fine. Creating the browser set will be a one time thing. I don't see this expanding to more and more sets.

> Also, as new jQuery versions may drop further browsers, you may end up needing to hardcode more than one browserSet and keep it in sync with the infra repo.

I don't think we'd ever want to handle many browser sets. To be honest, I wouldn't be surprised to see this entire thing go away in just a few months.

**Comment by scottgonzalez** [comment]
> Do you want me hardcode the browserSet for Core Git?

Yes, please.

> Is the name jquery-ui+jquery-3 OK? The regular UI browserSet is named jquery-ui.

Let's just use `jquery-ui-future`.

**Comment by mzgol** [comment]
> Let's just use `jquery-ui-future`.

OK, I'll do it. I'll just note that when we release jQuery 3.0.0 in a few months, `jquery-ui-future` will have to be used for that as well.

**Comment by mzgol** [comment]
I'm closing this PR; everything can be handled directly in #1646.

**Pull request closed without merging**
