### PR TITLE
Theme: Don't load the image sprite for `ui-icon-blank`

### PR DESCRIPTION
**Pull request by scottgonzalez**
Fixes #15193

### CODE REVIEW

**Comment by fnagel** [comment]
Hey @scottgonzalez, thanks for you PR Looks good to me. 

Any idea why you're no longer in the CLA list? Would you mind adding your email again? That would help with your other PR (#1840) too.

I really hope you and your family is doing well!

**Comment by scottgonzalez** [comment]
> Any idea why you're no longer in the CLA list?

Yes, because the foundation's administration and legal teams are a joke and they threw out years of valid signatures.

> Would you mind adding your email again? That would help with your other PR (#1840) too.

I do mind. I do not like the new CLA and the foundation's legal counsel has a very different interpretation of the new CLA than I do. As such, I will not sign it. However, there is nothing that should stop you from merging any of my PRs. See https://github.com/globalizejs/globalize/pull/703 for some more background.

> I really hope you and your family is doing well!

We are, thanks! I hope you're doing well too.

**Comment by fnagel** [comment]
@scottgonzalez Thanks for the response. Sadly, I'm not that sure if I'm able to merge this without valid CLA. 

@kborchers @StevenAyr Sorry to bother, but am I able to merge this or not? Do we really need to throw this bugfix away? Please take a look at #1840 too.

**Comment by kborchers** [comment]
@fnagel I am not in a position to make that call anymore and likely would have deferred to legal's advise even if I were. I am adding @brianwarner to the thread to get his take and he can get legal advise if necessary. Sorry I can't be more helpful but hopefully Brian can get this resolved for you quickly.

**Comment by fnagel** [comment]
@brianwarner Any news on this one?

**Comment by melloware** [comment]
I would also really like to see this merged as its a good performance improvement.

**Comment by fnagel** [comment]
Closed in favor of #1934

**Pull request closed without merging**
