### PR TITLE
Build: Update to qunit-assert-classes to V 1.0.1

### PR DESCRIPTION
**Pull request by arschmitz**

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Are you willing to add AMD to the module and do another release, then upgrade to that version?

**Comment by arschmitz** [comment]
Yup i meant to for v1 but forgot.

**Comment by arschmitz** [comment]
@scottgonzalez done

**Comment by jzaefferer** [comment]
Looks good to me.

**Comment by scottgonzalez** [comment]
:shipit:

**Pull request closed without merging**
