### PR TITLE
Sortable: Improved compatibility with flexbox

### PR DESCRIPTION
**Pull request by CBenni**
Added detection for flexbox into _isFloating, which improves the detection of where an item is moved to.

Ref: #9344

### CODE REVIEW

**Comment by CBenni** [comment]
The CLA does not want to detect my agreement, so im not gonna bother any longer. Closing.

**Comment by CBenni** [comment]
I was told to reopen this, and to request the CLA request to be fixed. Apparently multiple users have had this problem.

**Comment by scottgonzalez** [comment]
> I was told to reopen this, and to request the CLA request to be fixed. Apparently multiple users have had this problem.

Hi @CBenni. Can you please provide some more information about this? What specific problem were you told that other users have had? There are two problems with the current commits:

* One commit uses a noreply email address, which we don't accept because they're effectively the same as not having an email address.
* We request your full name, not a username or nick, but the CLA and commits have the name CBenni.

Beyond the CLA issues, we'd need a unit test showing that this fixes a problem. Are you able to add that? The test should fail without your patch and pass with your patch.

Thanks.

**Comment by CBenni** [comment]
I dont wish to disclose my real name publicly on the internet, as a basic safety precaution. If it is not possible to contribute without doing that, I will close again and use my private fork of the repo in the future.

**Comment by scottgonzalez** [comment]
> I dont wish to disclose my real name publicly on the internet, as a basic safety precaution.

That's fine. I've marked your CLA signature as valid. If you can squash your commits and make sure the new commit uses the proper email address, that should get the CLA check to pass. If you're not sure how to do that, you can read through http://contribute.jquery.org/CLA/status/?repo=jquery-ui&sha=1d62f0616cbfb6205d3525adbf81a940e5fc11ae or we can fix this when it's merged.

Are you willing to write the unit test?

**Comment by CBenni** [comment]
Ok, managed to squash and reupload, looks like the CLA worked aswell. Thanks @scottgonzalez 

I am willing, yet not quite sure how to, write unit tests. This is a one-line change that just modifies behaviour in some fairly specific cases, and has to do with position detection, mouse movement etc.

Obviously, a test would be possible for checking if the detection works, I am not sure at how useful that would be, since it only checks a helper function, which is likely to be changed or removed in case of an update.

If you could help me/tell me what is to be done, id be happy to help out, albeit I am a newbie when it comes to tests in javascript.

**Comment by CBenni** [comment]
Uh, sorry about that, the file isnt being updated properly on remote... On local, all checks pass, but the file isnt being reuploaded... What am I doing wrong? I used rebase, and then amended my commit, and pushed, but it does not update the remote file o.o

**Comment by CBenni** [comment]
@scottgonzalez If it helps, I have a demo that allows me to reproduce the bug on current versions, and see that the bug is fixed on my fork. I can add that to something somehow, some way.

**Comment by scottgonzalez** [comment]
We need a reduced test case showing the problem, along with a description of the specific improvement this patch provides. Given the test case that was provided in [the ticket](https://bugs.jqueryui.com/ticket/9344), the situation doesn't seem any different with this patch applied.

**Comment by scottgonzalez** [comment]
Closing due to inactivity. If you're still interested in working on this, please leave another comment addressing our question so we can reopen.

**Comment by Basster** [comment]
For all of you stubling about this issue, I found a pretty simple solution to get this working without maintaining a fork:

```js
$.widget('custom.flexboxSortable', $.ui.sortable, {
  _isFloating:  item => {
    return (/left|right/).test(item.css('float')) ||
      (/inline|table-cell/).test(item.css('display')) ||
      (/flex/).test(item.parent().css('display'));
  },
});

$('#sortable').flexboxSortable();
```

Thanks to [widget extension](https://learn.jquery.com/jquery-ui/widget-factory/extending-widgets/)

**Pull request closed without merging**
