### PR TITLE
Calendar / Datepicker: Fixes focus and tab index handling

### PR DESCRIPTION
**Pull request by fnagel**
* Merge with master
* Adjust file doc headers and meta data
* Calendar: Fix tab index for prev / next buttons
* Calendar: Fix ARIA / id attributes for multiple grids
* Datepicker: Fix focus after date selection and after leaving the widget by using tab
* Calendar: Do not rebuilt whole calendar when a date is selected (improves performance, fixes datepicker issues)

This should fix all "Focus related" issues in the wiki: http://wiki.jqueryui.com/w/page/12137778/Datepicker
See section "6 - Open issues being discussed" -> "Next Steps / ToDo"

### CODE REVIEW

**Comment by fnagel** [comment]
@scottgonzalez @jzaefferer 

Still not perfect but much improved a11y in this branch. I think we'll need to discuss some details of the proposed a11y specs in the wiki. The spec lacks information about how to handle multiple calendars, has some focus related difference and differs from the current implementation in general. 

Should I just merge all master / merge commits to datepicker branch? Somewhat ugly to review the actual changes at the moment...

@jzaefferer FYI: most of the above mentioned wiki issues (see PR description) have been reported by you in former PRs.

**Comment by scottgonzalez** [comment]
> Should I just merge all master / merge commits to datepicker branch? Somewhat ugly to review the actual changes at the moment...

I just review individual commits rather than using the full diff when the changes are this big. Next time you can do this as two branches. One with just the merge and then another with your changes on top of that. Then you can send the PR against the branch with just the merge so the PR diff only shows the new code.

**Comment by fnagel** [comment]
@scottgonzalez Reminder for another review (as asked for). 

Not sure which commits you have already seen but I guess this should be new for you: Fix tab index for prev / next buttons, Fix focus after date selection and after leaving the widget by using tab, Do not rebuilt whole calendar when a date is selected

**Comment by jzaefferer** [comment]
Is there any reason to have the merge commit in this PR? Seems like it makes things unnecessarily complicated to review.

**Comment by fnagel** [comment]
> If its a straightforward merge (no conflicts), yes please.

Datepicker will have always merge conflicts with master.

I will create two PRs next time (see Scotts response).

**Comment by jzaefferer** [comment]
Travis build failed with on date unit tests:
```sh
Testing tests/unit/date/date.html ..........F..
>> date: core - Months
>> Message: null
>> Actual: 11
>> Expected: -1
```
Is that the same issue we were looking at before, but with improved output? Or something else?

**Comment by fnagel** [comment]
> Travis build failed with on date unit tests

That's the issue we talked about in the last PR: https://github.com/jquery/jquery-ui/pull/1651#issuecomment-161357757 and following
Not sure why this happens, seems like a Globalize internal issue as this popped up from nowhere when December started.

**Comment by fnagel** [comment]
Closed in favor of #1660

@scottgonzalez @jzaefferer

**Pull request closed without merging**
