### PR TITLE
Build: Include all the files published to the CDN in npm/Bower packages

### PR DESCRIPTION
**Pull request by mgol**
Both unminified & minified versions of JS & CSS files are included, for all
themes, as well as images.

Fixes gh-2011

### CODE REVIEW

**Comment by mgol** [comment]
> I'm not aware how the release script works so not a really reliable review.

The main thing here is that in the `jquery-ui` package there will be a new `dist` folder that will contain everything we upload to the CDN; if this was included in the `1.13.1` release then dist in the npm package would contain everything from [https://github.com/jquery/codeorigin.jquery.com/tree/main/cdn/ui/1.13.1](https://github.com/jquery/codeorigin.jquery.com/tree/main/cdn/ui/1.13.1?rgh-link-date=2022-03-04T23%3A38%3A28Z), maintaining the directory structure.

Are you OK with that? The current `jquery-ui` package has no `dist` folder.

**Comment by mgol** [comment]
@fnagel can you say if you give a green light to the above?

**Comment by fnagel** [comment]
@mgol Just for my understanding, we then have those packages:

* Github tag (containing everything, incl. the new `dist` folder) https://github.com/jquery/jquery-ui/releases/tag/1.13.1
* A minimal CDN version https://github.com/jquery/codeorigin.jquery.com/tree/main/cdn/ui/1.13.1
* A minimal download builder version https://jqueryui.com/resources/download/jquery-ui-1.13.1.zip

The only new thing is that the Github tag / release download then includes the processed files, right?

**Review by fnagel — APPROVED** [review]

**Comment by mgol** [comment]
@fnagel yes, my understanding is the same.

**Pull request merged**
