### PR TITLE
Typo on README.ME (Link for CONTRIBUTING.md#environment-minimum-required.md)

### PR DESCRIPTION
**Pull request by TApplencourt**
Not a big deal but you know... :hamster: 
Have a nice day!

```
-To build jQuery UI, [setup your environment]([setting up your environment](CONTRIBUTING.md#environment-minimum-required)) and then run the following commands:
+To build jQuery UI, [setup your environment](CONTRIBUTING.md#environment-minimum-required) and then run the following commands:
```

### CODE REVIEW

**Comment by tjvantoll** [comment]
Thanks @TApplencourt. Can you please [sign our CLA](http://contribute.jquery.org/CLA/) so we can land this?

**Comment by TApplencourt** [comment]
I try [this](http://contribute.jquery.org/CLA/status/?repo=jquery-ui&sha=15aaa59484361e3784ba4b50e93e8c2dd41f8f82) like 10 time but i stull failed. I have to miss something... But feel free to close my merge, and change it by hand.

**Comment by scottgonzalez** [comment]
The problem is that your git config doesn't include your full name. I landed this with proper author information.

**Comment by TApplencourt** [comment]
Deep thx ! I will know for the next time =)

**Pull request closed without merging**
