### PR TITLE
Selectable: proper handling of inner scrolling

### PR DESCRIPTION
**Pull request by bleshik**
Fixes the bug http://bugs.jqueryui.com/ticket/13359

### CODE REVIEW

**Comment by bleshik** [comment]
It's been 3.5 month since I created the pull request... Could anyone tell me what I should fix in order to have it merged?

**Comment by rstepanenko** [comment]
yes, please accept it, we also need it!

**Comment by bleshik** [comment]
Another 6 months passed... Resolved the conflicts again, but not sure if I'll keep doing that:)

**Comment by jzaefferer** [comment]
We've been avoiding even reviewing this, since most of the logic in interactions is so crazy and fragile, that its very easy to introduce regressions (which are often worse than the original bug). There aren't nearly enough existing tests to compensate for that. I'm not sure how we can get out of that with the very limited resources we've got.

**Comment by bleshik** [comment]
@jzaefferer, thanks for responding! Got it! 
FYI, we've been using jquery-ui with the patch for 9 months with no problems, just saying...:)

**Comment by jzaefferer** [comment]
If we were to land this now, release it as part of 1.12.0 and we then get one or more bug reports due to this patch, would you be willing to help us fix those?

**Comment by bleshik** [comment]
@jzaefferer, sure, just assign those to me and I'll get them fixed.

**Comment by jzaefferer** [comment]
Alright, I'll land this then.

**Comment by jzaefferer** [comment]
Thank you! Will be released in 1.12.0-rc2 soon.

**Comment by bleshik** [comment]
Thanks!

**Pull request closed without merging**
