### PR TITLE
Fix day names Short & Min like in Arabic standard

### PR DESCRIPTION
**Pull request by zatamine**
The différence between MENA Arabic langage and Maghreb Arabic language about date is just month names and the value of the first day of the week.

Fixed

### CODE REVIEW

**Comment by scottgonzalez** [comment]
The values for `dayNamesMin` look correct, but the values for `dayNamesShort` don't seem to match the data in CLDR.

**Comment by scottgonzalez** [comment]
Closing due to inactivity.

**Comment by zatamine** [comment]
Hi @scottgonzalez , please can you give me more details about CLDR data and what do you mean by "don't seem to match"

Thanks

**Comment by rxaviers** [comment]
Hi @zatamine, you can find more details about CLDR at http://cldr.unicode.org/, specifically here (https://github.com/unicode-cldr/cldr-dates-modern/blob/master/main/ar/ca-gregorian.json) for gregorian calendar for Arabic.

**Comment by zatamine** [comment]
Thank you @rxaviers  it's more clear i'll push an other correction

**Pull request closed without merging**
