### PR TITLE
All: Consolidate `.removeAttr()` calls

### PR DESCRIPTION
**Pull request by scottgonzalez**
Hooray for jQuery 1.7+.

### CODE REVIEW

**Comment by jzaefferer** [comment]
Nice!

**Comment by jzaefferer** [comment]
I still have open style fix PRs for tabs and menus, probably better to land those first, then rebase this once.

**Comment by scottgonzalez** [comment]
Ok. What's another day since I've been waiting for classes to land this whole time anyway :-P

**Comment by jzaefferer** [comment]
All blockers are out of the way.

**Pull request closed without merging**
