### PR TITLE
Datepicker: Capitalize some Indonesian words

### PR DESCRIPTION
**Pull request by ddevsr**
Fixing typo bahasa in translation ID for Datepicker

### CODE REVIEW

**Comment by fnagel** [comment]
Thanks for your contribution!

We need some more reviews of the localization before merging this. Please see here for more info: https://jqueryui.pbworks.com/w/page/139157592/Adding%20translations

**Comment by fnagel** [comment]
Do I understand this right? You just removed the symbols before next and prev and did an first char to uppercase for some localization strings.

**Comment by fnagel** [comment]
Close and reopen for re-running the tests.

**Review by mgol — APPROVED** [review]
Thank you!

**Pull request merged**
