### PR TITLE
Update custom_render.html

### PR DESCRIPTION
**Pull request by markvantilburg**
Fixes mixed content error logging from the demo website over at jqueryui.com

```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
VM25 jquery-3.6.0.js:6591 Mixed Content: The page at 'https://jqueryui.com/resources/demos/selectmenu/custom_render.html' was loaded over HTTPS, but requested an insecure element 'http://www.gravatar.com/avatar/b3e04a4…?d=monsterid&r=g&s=16'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
```

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR. I think I'd like to update all HTTP URLs to HTTPS in one go, at least the ones used in demos. Would you like to try that?

**Comment by markvantilburg** [comment]
see also: #2183

**Comment by markvantilburg** [comment]
updated all http:// links in the demos also checked if these pages are available over https

**Review by mgol — APPROVED** [review]
Thank you! Especially for testing URL availability on HTTPS. 🙂

**Comment by mgol** [comment]
I also fixed #2183 and then I updated remaining HTTP URLs to HTTPS in #2244.

**Pull request merged**
