### PR TITLE
Remove useless IE8 code, fixes a bug I found using views_load_more fo…

### PR DESCRIPTION
**Pull request by joejoseph00**
IE8 related lines of code, harmless to remove and fixes bug for me.  Fixes bug for me when using jquery-ui with views_load_more (Drupal module)
…r Drupal with Chrome / Firefox latest versions.

### CODE REVIEW

**Comment by joejoseph00** [comment]
signed

**Comment by joejoseph00** [comment]
I signed and fixed the jshint issue

**Comment by dmethvin** [comment]
Closing as a stale branch. You can run tests and code checks locally to find issues before submitting a PR, see the README file.

**Comment by joejoseph00** [comment]
I signed the CLA , why is this so complicated just to remove some crap IE8 code?

**Pull request closed without merging**
