### PR TITLE
Autocomplete: Restore focus after clicking a menu item, if necessary

### PR DESCRIPTION
**Pull request by scottgonzalez**
Fixes #9201

Gotta love focus handling in IE.

### CODE REVIEW

**Comment by tjvantoll** [comment]
You should probably use `this.document`, and I'm guessing this is going to be susceptible to our [favorite IE9 bug](https://github.com/jquery/jquery-ui/blob/ea999e4776bb0fe67b1eff702f09fc5cb878bfe0/ui/dialog.js#L208-209) too.

**Comment by jzaefferer** [comment]
What TJ said...

**Comment by scottgonzalez** [comment]
I'll wait for #1478 before updating this.

**Comment by scottgonzalez** [comment]
Updated using `$.ui.safeActiveElement()`.

**Comment by jzaefferer** [comment]
:+1:

**Comment by tjvantoll** [comment]
:+1:

**Pull request closed without merging**
