### PR TITLE
Slider: Add demo for custom handle

### PR DESCRIPTION
**Pull request by scottgonzalez**
Fixes #15023

### CODE REVIEW

**Comment by jzaefferer** [comment]
Works well with mouse, doesn't work with keyboard. Do we expect the user to add `tabindex` to the custom handle markup? Or is this a spinner bug?

**Comment by jzaefferer** [comment]
To me it seems like a bug - we should also add a test.

**Comment by scottgonzalez** [comment]
Yeah, we should handle this inside the slider.

**Comment by scottgonzalez** [comment]
Updated to apply `tabIndex` to all handles; includes a test.

**Comment by jzaefferer** [comment]
Updated diff looks good. Haven't tested it again though.

**Pull request closed without merging**
