### PR TITLE
Core: Handle IE11 bug with document.activeElement in iframes

### PR DESCRIPTION
**Pull request by scottgonzalez**
Fixes #11539

How has this not come up before?

### CODE REVIEW

**Comment by jzaefferer** [comment]
Looks fine, as in, I realize that being angry at IE doesn't help, so why not add more workarounds on top of existing workarounds.

**Comment by jzaefferer** [comment]
PS: https://twitter.com/jacobrossi/status/580493801086705664

**Comment by jacobrossi** [comment]
@jzaefferer @scottgonzalez do either of you know if this still repros in the EdgeHTML engine? if not, can you check at remote.modern.ie? I'll get a bug filed and prioritized if it does.

**Comment by scottgonzalez** [comment]
@jacobrossi I'll be working on a reduced test case tomorrow and I'll test against remote.modern.ie at that time.

**Comment by scottgonzalez** [comment]
It appears to work properly on remote.modern.ie. This is as far as I got for reducing it: http://jsbin.com/fejituname/1/

**Comment by jacobrossi** [comment]
Great, then that means it works OK in Project Spartan too. I realize that doesn't help you out with IE. But it's still good to see it's fixed nonetheless.

**Pull request closed without merging**
