### PR TITLE
Calendar / Datepicker: Update tests to QUnit 2.x, fix jscs errors

### PR DESCRIPTION
**Pull request by fnagel**

### CODE REVIEW

**Comment by fnagel** [comment]
Tests fail, but that seem related to some Spinner Widget tests.

**Comment by jzaefferer** [comment]
Its interesting that the spinner tests fail on `globalize-runtime/ja-JP`
```
Testing tests/unit/spinner/deprecated.html >> PhantomJS error:
>>  Error: Script error for: globalize-runtime/ja-JP
>> http://requirejs.org/docs/errors.html#scripterror 
>>  [ { file: 'file:///home/travis/build/jquery/jquery-ui/external/requirejs/require.js',
>>     line: 141,
>>     function: 'defaultOnError' },
>>   { file: 'file:///home/travis/build/jquery/jquery-ui/external/requirejs/require.js',
>>     line: 545,
>>     function: 'onError' },
>>   { file: 'file:///home/travis/build/jquery/jquery-ui/external/requirejs/require.js',
>>     line: 1689,
>>     function: 'onScriptError' } ]
```
Opening the spinner tests in the browser also shows a failure: It fails to load `http://localhost:8765/external/globalize/globalize-runtime/ja-JP.js`, since that is a 404. 

For me that also happens on the datepicker branch, so it seems unrelated to this branch. But since the datepicker branch is making changes to how Globalize is loaded/used, its surely related to datepicker in general.

**Comment by fnagel** [comment]
Should I go ahead then and merge this? I've got some more, smaller PRs based upon this one ready to be pushed.

Seems a merge commit removed our globalize-old workaround for spinner tests.

**Comment by jzaefferer** [comment]
Yeah, let's merge it.

**Pull request merged**
