### PR TITLE
Tabs: Rename ui-tab class to ui-tabs-tab for consistent prefixes

### PR DESCRIPTION
**Pull request by jzaefferer**
Ref jquery/api.jqueryui.com#256
Ref #7053

I figured that we can keep it simple for this trivial change and not create separate unit test files.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
This isn't documented, but if we're going to deprecate, we should create a ticket for the deprecation and and a ticket for the removal.

**Comment by jzaefferer** [comment]
Created http://bugs.jqueryui.com/ticket/12061 and http://bugs.jqueryui.com/ticket/12063 and updated this PR to reference the first ticket.

**Comment by scottgonzalez** [comment]
Looks good.

**Comment by arschmitz** [comment]
:+1:

**Pull request merged**
