### PR TITLE
check if parentNode exists before removeChild

### PR DESCRIPTION
**Pull request by babakhanov**
got rid of `Cannot read property 'removeChild' of null`

### CODE REVIEW

**Comment by scottgonzalez** [comment]
When does this occur? We need a [ticket](https://bugs.jqueryui.com/newticket) with a reduced test case showing that a bug exists.

**Comment by mannykary** [comment]
Any idea if this will be approved? I found this relevant ticket https://bugs.jqueryui.com/ticket/6054

**Comment by md5** [comment]
I think the `if ( !this.cancelHelperRemoval ) {` should also be updated to `if ( !this.cancelHelperRemoval && this.helper ) {` to fix the scenario in the linked ticket.

**Comment by dmethvin** [comment]
Closing as stale.

**Pull request closed without merging**
