### PR TITLE
Tooltip: Remove use of `$.parseJSON()`

### PR DESCRIPTION
**Pull request by scottgonzalez**
Also fixes the module loading for the tooltip animations visual test.

Fixes #14903

### CODE REVIEW

**Comment by rxaviers** [comment]
The JSON update LGTM. I'm unfamiliar on how the `data-modules` attribute from the script tag  is used by the demo.

**Comment by scottgonzalez** [comment]
> I'm unfamiliar on how the `data-modules` attribute from the script tag is used by the demo.

They're just split on spaces and then injected into a `require()` call.

**Comment by rxaviers** [comment]
> They're just split on spaces and then injected into a `require()` call.

Ok, thanks for the clarification.

**Comment by jzaefferer** [comment]
:+1:

**Pull request closed without merging**
