### PR TITLE
Tests: Use demo bootstrap for visual tests

### PR DESCRIPTION
**Pull request by jzaefferer**
Adds data-base-url and data-composite options and fixes a missing entry for effects. Otherwise just applies the same conversion as already applied to demos, sometimes moving a `<style>` element to the right place.

### CODE REVIEW

**Comment by jzaefferer** [comment]
Fixing build issue...

**Comment by scottgonzalez** [comment]
Since the base URL only ever has two possible values, can we just check the path for the `script` and figure out the base inside the bootstrap code?

Also, some of these lines became very long, can we break the attributes onto multiple lines when they're long?

**Comment by jzaefferer** [comment]
> Since the base URL only ever has two possible values, can we just check the path for the script and figure out the base inside the bootstrap code?

Done, replaced with a check for `window.location.pathname.indexOf( "demos/" ) !== -1`

> Also, some of these lines became very long, can we break the attributes onto multiple lines when they're long?

Without the `data-base-url` it got better. Also inserted some linebreaks on the remaining very-long lines. I also finally figured out why `data-modules="effects-all"` wasn't working. Now it works for both demos and visual tests.

**Comment by scottgonzalez** [comment]
That's much better.

**Pull request merged**
