### PR TITLE
Authors: Update

### PR DESCRIPTION
**Pull request by siebrand**
Update email address for Siebrand Mazeland

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Please make this change through `.mailmap`. Any manual change to `AUTHORS.txt` will be overridden.

**Comment by siebrand** [comment]
Can you please elaborate? I don't know what .mailmap is.

**Comment by scottgonzalez** [comment]
It's another file in the root of this repo. You can read about it in the [git-shortlog documentation](https://git-scm.com/docs/git-shortlog#_mapping_authors). The line you'll want to add is:

```
Siebrand Mazeland <siebrand@kitano.nl> <s.mazeland@xs4all.nl>
```

**Comment by siebrand** [comment]
Thank you, Scott. I'll open a new pull request.

**Pull request closed without merging**
