### PR TITLE
Added bower.json

### PR DESCRIPTION
**Pull request by andremleblanc**

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Why would you want to add this to 1-10-stable?

**Comment by andremleblanc** [comment]
We're using an older library that utilizes 1-10-stable and I'd like to load it through bower into my Rails app using Rails-Assets.org.

**Comment by scottgonzalez** [comment]
Why aren't you using https://github.com/components/jqueryui? `bower install jquery-ui#1.10.4` already works just fine.

**Comment by andremleblanc** [comment]
Oops! My trouble ended up being a gem conflict, thanks for your help.

**Pull request closed without merging**
