### PR TITLE
Tabs: Add option forceLocal

### PR DESCRIPTION
**Pull request by tjmonk15**
Adds an option to Tabs to have them treat all hrefs as local selectors

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Sorry, but we won't add options that lie about what's happening.

**Comment by tjmonk15** [comment]
How does this option lie about anything?

**Comment by scottgonzalez** [comment]
It says that the tabs are pointing to local content when they're not. This has been discussed ad nauseam and will not be changed. See https://bugs.jqueryui.com/ticket/7822 for more information.

**Comment by scottgonzalez** [comment]
You can of course make your own extension to add such an option, it just won't be accepted upstream.

**Pull request closed without merging**
