### PR TITLE
Sortable: scroll connected sortable on a drag operation

### PR DESCRIPTION
**Pull request by AllSeeingEye**
Works for connected sortables, as well as draggable connected to a sortable.

Fixes #3173.

Test included, CLA signed.

### CODE REVIEW

**Comment by vendethiel** [comment]
Hi,

is there a reason no one has looked at this? :)

**Comment by AllSeeingEye** [comment]
Please look at this. Should I try to resubmit / rebase because of the conflicts?

**Comment by scottgonzalez** [comment]
A rebase would be great. Would you mind also looking at https://github.com/jquery/jquery-ui/pull/1793 which deals with scrolling? If the other PR looks good to you, it might be good to just rebase on top of that.

**Comment by scottgonzalez** [comment]
Closing due to inactivity.

**Pull request closed without merging**
