### PR TITLE
Button: Escape label option as text

### PR DESCRIPTION
**Pull request by jzaefferer**
Fixes jquery/api.jqueryui.com#281

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Button labels have always been HTML and this is sort of a requirement since you can initialize a button that already has a label which contains HTML. A change like this would require discussion, proper ticket, upgrade guide, etc.

**Comment by scottgonzalez** [comment]
Note that the bug that was actually reported is legit. The `closeText` option on dialog has to be treated as text. But that doesn't mean that the more generic application of button labels must be limited as well.

**Comment by jzaefferer** [comment]
Okay, we can discuss that in the meeting today. If we stick with html labels, we need to add a test for that.

**Comment by jzaefferer** [comment]
Closing this, will create a PR to add tests for the current behaviour instead, and patch dialog to escape the `closeText` option.

**Pull request closed without merging**
