### PR TITLE
All: Drop support for jQuery 1.6.x

### PR DESCRIPTION
**Pull request by jzaefferer**
Affects core, effects, position and widget. Only position has unit tests that fail with jQuery 1.6 without the workaround.

Drops the 1.6.x copies jQuery of jQuery and removes them from the select in the testsuites.

Fixes [#10723](http://bugs.jqueryui.com/ticket/10723)

### CODE REVIEW

**Comment by mikesherov** [comment]
I suppose `bind` to `on` is for another PR?

**Comment by mikesherov** [comment]
LGTM

**Comment by arschmitz** [comment]
@mikesherov i have an old branch im going to update and submit that removes our dependency on the event alias core module might make sense to do it at the same time since no in all supported versions bind is an event alias?

**Comment by tjvantoll** [comment]
:+1:

**Comment by scottgonzalez** [comment]
There are support comments in tests too.

**Comment by jzaefferer** [comment]
Added a commit that updates core and tooltip tests. Verified both suites tests pass everywhere using browserstack-runner locally.

**Comment by scottgonzalez** [comment]
Looks good.

**Comment by jzaefferer** [comment]
Landed. @mikesherov @arschmitz yeah, updating bind/on should be done elsewhere. There's currently no ticket (for 1.12) for that.

**Pull request closed without merging**
