### PR TITLE
Resizable: Containment works properly when child element has margin

### PR DESCRIPTION
**Pull request by tswaters**
Fixes #12980

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Thanks for your interest in jQuery UI. I'm sorry that the team has been silent for so long. We're in a not-so-great situation where most changes to the interaction plugins, even bug fixes with tests, result in unforeseen regressions. This is our fault for not having good test coverage on the interactions and building complex APIs that cause all kinds of strange behaviors when used together.

We will be rewriting every interaction widget, with some of them already underway. As a result, we will be closing this PR in order to stay with the status quo rather than risk more regressions. At least we know that existing users won't experience new bugs. Again, I apologize for the delay and the lack of review, but we're very grateful for your contribution and hope you will be contributing again.

**Comment by tswaters** [comment]
Where is the work for rewriting interaction widgets being undertaken?

**Comment by scottgonzalez** [comment]
> Where is the work for rewriting interaction widgets being undertaken?

In the [interactions branch](https://github.com/jquery/jquery-ui/tree/interactions).

**Comment by tswaters** [comment]
Would it be beneficial to send a PR against that branch?  Can't help but notice the last commit against it was 2 years ago...

**Comment by scottgonzalez** [comment]
> Would it be beneficial to send a PR against that branch?

Absolutely. If you're interested in helping with the interaction rewrites, we would be happy to go over the plans and figure out a good path forward for you. However, I will say that if your interest is in resizable specifically, that you'll be working from nothing as we have not begun the resizable rewrite yet.

The best method for communication with the team is IRC (see the [contributing guidelines](https://github.com/jquery/jquery-ui/blob/master/CONTRIBUTING.md) for details). But if you're not comfortable with IRC, feel free to just email me.

> Can't help but notice the last commit against it was 2 years ago...

That's because the person who was focused on the rewrites hasn't been active for a while and the team's main focus has been elsewhere. You can see what our focus is on our [roadmap](http://wiki.jqueryui.com/w/page/12138038/Roadmap). You'll notice that our next release (1.13) includes the new interaction base and the draggable rewrite, so these are about to become active again.

**Comment by jzaefferer** [comment]
There's also https://github.com/jquery/jquery-ui/pull/1611 which isn't quite as old/stale, but also needs helps. Finishing the move to pointer events will benefit all interactions.

**Pull request closed without merging**
