### PR TITLE
Build: Update to the latest version of Grunt & many other packages

### PR DESCRIPTION
**Pull request by mikhey**
Closes gh-15112

### CODE REVIEW

**Comment by mikhey** [comment]
In this configuration I was able to update grunt to the latest version and have it _still_ process & test the files without failure.  

I would recommend migrating away from jscs to eslint as the jscs team has been working with eslint for some time (please see the [node-jscs repo](https://github.com/jscs-dev/node-jscs), their [Medium article](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2) and [user guide for migrating to eslint](https://eslint.org/docs/user-guide/migrating-from-jscs)).  However, that being said, I've attempted this locally, and the tests resulted in failure because of syntax errors (mainly with spacing) which I believe may be related to the jquery eslint rule set.  

In addition, there was some CSS & HTML syntax rule issues when I upgraded grunt-contrib-csslint and grunt-html to latest.

I can upgrade these as well, however that would mean addressing the syntax issue(s) as well.  If that's not an issue, I can proceed with that as well.

**Comment by mikhey** [comment]
Just saw the Travis CI result which is what I was seeing when I updated grunt-jscs. It worked for me locally, but that may have been a fluke as I was upgrading/downgrading npm packages.  

Should I address the syntax warnings as well?

**Comment by dmethvin** [comment]
@mikhey Thanks, and sorry for the long delay! I agree we'd like to move to eslint, are you interested in doing that? Just the upgrade to the latest grunt will help.

**Comment by mikhey** [comment]
My apologies for not getting back to you sooner!  I would love to help out with that!

**Review by mgol — APPROVED** [review]

**Comment by mgol** [comment]
Landed, thanks!

**Comment by mgol** [comment]
I updated a few more packages & landed the PR. Thanks!

**Comment by mgol** [comment]
I updated a few more packages & landed the PR in a22361dbe491c494a87f38600d9c1f91aa07d3e0. Thanks!

**Comment by mgol** [comment]
@mikhey Are you still interested in trying to migrate us to ESLint? We'd use [`eslint-config-jquery`](https://www.npmjs.com/package/eslint-config-jquery).

**Pull request merged**
