### PR TITLE
Selectmenu: Add disabled default options to product selection demo

### PR DESCRIPTION
**Pull request by fnagel**
As @jzaefferer proposed, I've added a "please choose" option with selected and disabled attribute.

### CODE REVIEW

**Comment by jzaefferer** [comment]
Looks good to me. I'll let someone else take a look as well, hopefully we're not on the wrong track.

**Comment by fnagel** [comment]
Yeah, not sure if the empty initial state is what we want.

**Comment by scottgonzalez** [comment]
What is the intent of this change?

**Comment by scottgonzalez** [comment]
@jzaefferer We're wondering why we explicitly want to demo this behavior since it's just standard `<select>` behavior.

**Comment by jzaefferer** [comment]
We didn't have a single demo or even visual test that was using this standard `<select>` behaviour. I think its worth showing that it still works for `selectmenu`.

**Comment by scottgonzalez** [comment]
Can we find a better demo for it? A product selector that starts with no preview at all isn't great UX.

**Comment by tjvantoll** [comment]
Agreed that this is bad UX. What if we just added a fourth select to the [main demo](http://view.jqueryui.com/master/demos/selectmenu/default.html) with a more common use case for this functionality—maybe salutation?

**Comment by scottgonzalez** [comment]
That sounds good to me.

I'll close this and someone can send a new PR with a different change.

**Pull request closed without merging**
