### PR TITLE
Mouse: Don't stop propagation of mouseup

### PR DESCRIPTION
**Pull request by hmethvin**
Fixes #10818

### CODE REVIEW

**Comment by jzaefferer** [comment]
Looks good to me!

**Comment by jzaefferer** [comment]
Thank you!

**Comment by jzaefferer** [comment]
The new test is failing on IE8: http://swarm.jquery.org/result/740908 "Expected 1 assertions, but 0 were run"

**Comment by scottgonzalez** [comment]
Heh. Welcome to 2009 where DOM Level 2 Events is the current spec and events don't bubble up to the window.

I'll send a PR to skip the test in IE 8 since the tested behavior actually shouldn't occur in that browser.

**Pull request merged**
