### PR TITLE
Calendar: minor fixes

### PR DESCRIPTION
**Pull request by fnagel**
Some minor items from the wiki todo list.

### CODE REVIEW

**Comment by jzaefferer** [comment]
I reviewed the individual commits, again no actual testing. Looks good to me.

**Comment by fnagel** [comment]
Needed to change styles for button elements. Added fix for multiple month border style.

**Comment by fnagel** [comment]
Updated day item generation to use button elements only.

**Comment by jzaefferer** [comment]
Travis build failed, including calendar issues.

**Comment by jzaefferer** [comment]
Looks the same as before in Firefox and Chrome, so that's good!

**Comment by fnagel** [comment]
Fixed broken calendar unit test.

**Comment by fnagel** [comment]
Rebased on to rebased datepicker branch. Thanks @scottgonzalez!

**Comment by scottgonzalez** [comment]
@fnagel What's the status of this? Are you waiting for another review from @jzaefferer?

**Comment by fnagel** [comment]
@scottgonzalez Waiting for another review (if needed) by Jörn or yourself. Otherwise this could be merged right away.

**Comment by fnagel** [comment]
@scottgonzalez Updated as suggested.

**Comment by scottgonzalez** [comment]
Looks good.

**Comment by scottgonzalez** [comment]
@fnagel What's holding this up?

**Comment by fnagel** [comment]
@scottgonzalez Nothing specific, just hardly free time...

**Comment by scottgonzalez** [comment]
Merged into datepicker branch 2ea46ae1afaa777aa129c1a06e8ea0152fa616be...bbe1eff498ac7129b0240d0ff17c7d20685bf2a3

**Pull request closed without merging**
