### PR TITLE
Package: Remove Scott González from maintainers

### PR DESCRIPTION
**Pull request by scottgonzalez**

### CODE REVIEW

**Comment by TheWitness** [comment]
I saw a few comments from his twitter feed in 2016 and 2017 that, if you read between the lines, would indicate that the project was over encumbered with bureaucracy (read as legal) and that there may have been issues with the cadence of the project that were suffocating both the project and it's key developer.  

It's sad to see such a huge contributor move on, but we all have lives to live and priorities do change.  I mean like, for example, raising and feeding ones young and growing families.  Those things should be the most important things in each and every one of our lives, because in the end, no one get's out of this life alive and its no fun being alone.

That being said, jQuery and jQueryUI are important tools for projects throughout the planet.  May they continue to develop and evolve.  I, for one, hope this project, as well as jQuery, can keep its center and move forward into the future.

**Comment by scottgonzalez** [comment]
Legal issues were part of it, but there were a lot of other issues from the foundation as well. There was a quick downward spiral when Kris Borchers took over as Executive Director for jQuery Foundation. Since then the foundation stopped hosting conferences (which doubled as team and board meetings), the individual membership program was cancelled, all of the most active directors from the board were removed one by one in "clever" ways, and our budgets were severely cut.

At this point, there is practically no organization within the foundation. All of their initiatives have had no visible progress, most of the infrastructure and content is unmaintained (the foundation as a whole maintained about two dozen sites with a lot of custom infrastructure behind it), and they tout transparency while being ridiculously opaque with their operations. Legal changes were forced upon all projects with no discussion and the legal team refused to engage in conversations about differences in understanding of the changes.

Kris also lied to the Dojo Foundation about how the projects would be treated and the support the foundation would provide when they approached them to merge with jQuery Foundation and rebrand as JS Foundation. Part of the merger included adding @dylans as a director to represent the incoming projects. During the rebranding as JS Foundation, Kris once again used his clever ways to kick Dylan off the board.

I kept quiet about all of the internal problems for a few years, but it has gotten to the point where I am willing to publicly discuss anything and everything about my experiences with the foundation. I will say that if anyone is wondering why there hasn't been a single commit to master in a full year, it's because the foundation created a situation in which developers who once were willing to commit 20, 40, even 70 hours per week to jQuery-related projects now have no desire to interact with the foundation in any way.

**Comment by melloware** [comment]
@scottgonzalez Why not fork this great project and keep maintaining it?  The license will allow it I believe and there is no need to keep it under the Foundation if the Foundation is no longer supporting or maintaining it?

**Comment by fnagel** [comment]
Closed in favor of #1934

**Pull request closed without merging**
