### PR TITLE
Resizable: Fix resizing of elems with `box-sizing: border-box`

### LINKED ISSUE #1979: border-box and dialog resizing problem
Having this CSS:
```
*
{
    box-sizing: border-box;
}
```

If you try to resize a dialog, then the inner content (ui-dialog-content) is resized wrongly

See this fiddle: [http://jsfiddle.net/QBqff/2/](http://jsfiddle.net/QBqff/2/)

A workaround is suggested in [https://bugs.jqueryui.com/ticket/9137](https://bugs.jqueryui.com/ticket/9137)

Using this CSS:
```
.ui-resizable, .ui-resizable * {
    box-sizing: content-box;
}
```

### PR DESCRIPTION
**Pull request by mcanepa**
fixes #1979

### CODE REVIEW

**Comment by mgol** [comment]
If you're interested in finishing this, there are some existing `autoResize` tests in [`tests/unit/resizable/options.js`](https://github.com/jquery/jquery-ui/blob/933ce5d779135ad04734f14c50b38f9a8d8564f5/tests/unit/resizable/options.js), you'd need to add a new test there.

**Comment by mcanepa** [comment]
I'll try my best...

This will be my first encounter with a unit test so any help from anyone it would be very much appreciated

**Comment by mcanepa** [comment]
@mgol just added a test. I hope it's ok!

**Comment by mcanepa** [comment]
hello @mgol @fnagel 

Any chance for this issue to be reviewed?

**Review by mgol — APPROVED** [review]
Thank you! Looks good to me now. I'll still wait a bit for @fnagel's review before merging.

**Review by fnagel — APPROVED** [review]
+1 by reading

**Comment by mgol** [comment]
Landed, thanks!

**Pull request merged**
