### PR TITLE
Add jQuery as a dependency

### PR DESCRIPTION
**Pull request by cusspvz**
I'm currently developing a package compiler / loader and manager for browsers and WebView apps frameworks such as phonegap/cordova. This PR will defines `jquery@2.x` as a production dependency for those who `require('jquery-ui')`.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
But that's wrong for everyone who uses npm, which is effectively everyone contributing to the project.

**Comment by cusspvz** [comment]
I would like to offer official **requirehit** support for **jquery** and **jquery-ui**.

Would you consider to have it supported via our custom configuration file as soon as we release a production-ready version?

**Comment by scottgonzalez** [comment]
Nope. You can do that in your own package.

**Comment by cusspvz** [comment]
We cannot, at all, set dependencies for each package. Seems that `jquery-ui` will be unsupported by our *sugar* methods. Thanks for your time.

**Pull request closed without merging**
